# Generated by Django 5.2.6 on 2025-09-11 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('cleats', 'Cleats'), ('glove', 'Glove'), ('shin guard', 'Shin guard'), ('sock', 'Sock'), ('jersey', 'Jersey'), ('football', 'Football')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
