# Generated by Django 5.2.6 on 2025-09-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cleat', 'Cleat'), ('glove', 'Glove'), ('shin guard', 'Shin guard'), ('sock', 'Sock'), ('jersey', 'Jersey'), ('football', 'Football')], default='jersey', max_length=20),
        ),
    ]
