# Generated by Django 5.2.6 on 2025-09-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cleats', 'Cleats'), ('gloves', 'Gloves'), ('shin guards', 'Shin guards'), ('socks', 'Socks'), ('jerseys', 'Jerseys'), ('football', 'Football')], default='jersey', max_length=20),
        ),
    ]
